### ISSUE TITLE
how can I reach you by email

### ISSUE THREAD

**Issue by jomollin** [deep-insights-ai/covid-19-classifier#11]
we are interested to integrate your solution into myCare2x HIS / EMR and tried to send an email.

your email mailto:kaplan@deep-insights.ai isn't accessible 

write me mollin@mycare2x.net or call me +49 171 8017700

**Comment by GastonLagaffe2013** [comment]
Salut,
I have trained a ResNeXt50_32x4d network and achieved a accuracy of 98% with a confidence > 95% and would also like to share my results with you. Have the same error on your mail server replying that the given mail address does not exist
Ciao, Dr. Mathias Wilhelm

**Comment by aaronkaplan** [comment]
contact established
